# Generated by Django 5.0.3 on 2024-03-13 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('userConcerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
