# Generated by Django 5.0.3 on 2024-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visarequests',
            name='status',
            field=models.CharField(choices=[('evaluation', 'Etude en cours'), ('approved', 'Approuvées'), ('rejected', 'Rejetées')], default='evaluation', max_length=255),
        ),
    ]
